### ISSUE TITLE
All my .dat files were wiped and no backups were created?

### ISSUE THREAD

**Issue by moude3** [Exomanz/ConsistentSaberColors#1]
Hi! I just installed this mod. In the description, it said it was supposed to create a backup folder in userdata for PlayerData.dat and settings.dat? If it's meant to do that I do not see it and it just wiped all my .dat files. I saw it created some .bak files in the LocalLow folder. I checked all those and looks like it didn't back up those files correctly.

![explorer_rgYlkljIyg](https://user-images.githubusercontent.com/48892029/131523938-23c73463-bb81-40c2-afe8-b9e91943807c.png)

**Comment by Exomanz** [comment]
Hi there. 

Thank you for this report--this is actually the second documented case of this happening, so now I know that this isn't isolated and/or a fluke. What's even weirder is that, as the host, it works perfectly fine. I'll be taking a look into this as soon as possible.

I would like to apologize for any data loss that may have occurred.

**Comment by moude3** [comment]
Somehow my controller settings survived but not anything else. If you want me to test anything I'm open for it.

**Comment by RafaelSchridi** [comment]
Same thing happend to me after changing sound delay, sadly my backup is 8 months old.

**Comment by Exomanz** [comment]
I've extensively overhauled and rewrote every system that this mod utilizes. After testing closely with three people, every system seems to work as expected. 

A pre-release has been put out on the [releases](https://github.com/Exomanz/ConsistentSaberColors/releases/rel_0.1.0_alpha) page, which aims to fix every bug that may have been presented.

I'll keep this issue open for a couple more days until it's confirmed that everything is working normally.

**Comment by Exomanz** [comment]
I'm going to go ahead and close this issue as I haven't heard anything else from players that these bugs are still occurring.

If something comes back up, let me know right away by DM or opening another issue. Thank you again for the initial bug report.
